// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// FOS
Rcpp::NumericVector FOS(Rcpp::NumericMatrix X, Rcpp::NumericVector Y);
RcppExport SEXP HDIM_FOS(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(FOS(X, Y));
    return rcpp_result_gen;
END_RCPP
}
